# .github/workflows/main.yml
name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      my_param:
        description: 'my param'
        required: true
        default: 'Hello, main workflow!'

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print parameter
        run: echo 'Parameter:' ${{ inputs.my_param }}

  invoke_reusable_workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      my_param: ${{ inputs.my_param }}
