# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      cli_params:
        description: 'Run tests by cli-params'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}"\
          https://api.github.com/repos/MarianaNun/postman-test/dispatches \
          -d '{"event_type":"some_event","client_payload":{"name":"sample-name","uuid":"uuid-1"}}'
