# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      cli_params:
        description: 'Run tests by cli-params'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --request POST \
             https://api.github.com/repos/MarianaNun/postman-test.git/dispatches \
            --data '{"event_type": "some_event", "client_payload": { "foo": "bar" }}'
