# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      cli_params:
        description: 'Run tests by cli-params'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['MarianaNun/postman-test.git']
    timeout-minutes: 5
    steps:
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            --request POST \
            --data '{"event_type": "some_event", "client_payload": { "foo": "bar" }}' https://api.github.com/repos/${{ matrix.repo }}/dispatches
